//! F* source emission.
//!
//! Translates our intermediate AST directly into F* AST constructor
//! applications. The emitter does NOT compute types, contexts, or
//! verification conditions — it just constructs the AST. The F* type
//! system does the verification: if the emitted module typechecks,
//! the programme is valid.

use std::fmt::Write;

use super::fstar_ast::*;

/// Emit a complete F* module from a BpfObject.
pub fn emit_module(obj: &BpfObject, module_name: &str) -> String {
    let mut out = String::new();

    writeln!(out, "(* Auto-generated by bpf2fstar from {} *)", obj.source_file).unwrap();
    writeln!(out, "module {}", module_name).unwrap();
    writeln!(out).unwrap();
    writeln!(out, "open BPF.AST.Types").unwrap();
    writeln!(out, "open BPF.AST.Expr").unwrap();
    writeln!(out, "open BPF.AST.Stmt").unwrap();
    writeln!(out, "open BPF.AST.Decl").unwrap();
    writeln!(out, "open BPF.VarCtx").unwrap();
    writeln!(out, "open BPF.ValClass").unwrap();
    writeln!(out, "open BPF.Helpers").unwrap();
    writeln!(out).unwrap();

    for map in &obj.maps {
        emit_map_def(&mut out, map);
        writeln!(out).unwrap();
    }

    for prog in &obj.progs {
        emit_prog(&mut out, prog);
        writeln!(out).unwrap();
    }

    out
}

fn emit_map_def(out: &mut String, map: &MapDef) {
    writeln!(out, "let map_{} : map_def = {{", map.name).unwrap();
    writeln!(out, "  map_name = \"{}\";", map.name).unwrap();
    writeln!(out, "  map_type = MapHash;").unwrap();
    writeln!(out, "  map_key_type = {};", emit_ctype(&map.key_type)).unwrap();
    writeln!(out, "  map_val_type = {};", emit_ctype(&map.value_type)).unwrap();
    writeln!(out, "  map_max_entries = {};", map.max_entries).unwrap();
    writeln!(out, "}}").unwrap();
}

fn emit_prog(out: &mut String, prog: &BpfProg) {
    writeln!(out, "(* Programme: {} SEC(\"{}\") *)", prog.name, prog.section).unwrap();
    writeln!(out).unwrap();

    // The programme body is a single stmt constructed from the C function body.
    // The initial context has "ctx" as PtrToCtx 0.
    // Annotate with initial context so F* can infer the chain
    writeln!(out, "let body_{} : stmt [(\"ctx\", PtrToCtx 0)] _ =", prog.name).unwrap();
    emit_stmts(out, &prog.body, 2);
    writeln!(out).unwrap();
}

/// Emit a list of statements as a nested Seq chain.
fn emit_stmts(out: &mut String, stmts: &[Stmt], indent: usize) {
    let pad = " ".repeat(indent);
    match stmts.len() {
        0 => write!(out, "{}Nop", pad).unwrap(),
        1 => emit_stmt(out, &stmts[0], indent),
        _ => {
            writeln!(out, "{}Seq (", pad).unwrap();
            emit_stmt(out, &stmts[0], indent + 2);
            writeln!(out, ")").unwrap();
            writeln!(out, "{}(", pad).unwrap();
            emit_stmts(out, &stmts[1..], indent + 2);
            writeln!(out, ")").unwrap();
        }
    }
}

/// Emit a single statement as an F* AST constructor.
fn emit_stmt(out: &mut String, stmt: &Stmt, indent: usize) {
    let pad = " ".repeat(indent);
    match stmt {
        Stmt::Declare(name, ty, init) => {
            match init {
                None => {
                    write!(out, "{}Declare \"{}\" {}", pad, name, emit_ctype(ty)).unwrap();
                }
                Some(expr) => {
                    // Declaration with initialiser = Declare + Assign in sequence
                    // But our AST Declare only adds Uninit. So we emit Seq(Declare, Assign).
                    // However, Assign takes an expr and a val_class.
                    // For now, model as CallAssign if it's a helper call, otherwise as
                    // a plain assignment.
                    match expr {
                        Expr::Call(func_name, args) => {
                            // Helper call: use CallAssign
                            writeln!(out, "{}Seq (Declare \"{}\" {})", pad, name, emit_ctype(ty)).unwrap();
                            write!(out, "{}    (CallAssign \"{}\" ", pad, name).unwrap();
                            emit_helper_ref(out, func_name);
                            write!(out, " [").unwrap();
                            for (i, arg) in args.iter().enumerate() {
                                if i > 0 { write!(out, "; ").unwrap(); }
                                emit_ctype_of_expr(out, arg);
                            }
                            write!(out, "] ").unwrap();
                            emit_val_class_for_helper(out, func_name);
                            write!(out, ")").unwrap();
                        }
                        _ => {
                            // Simple initialiser: Declare then Assign
                            writeln!(out, "{}Seq (Declare \"{}\" {})", pad, name, emit_ctype(ty)).unwrap();
                            write!(out, "{}    (Assign \"{}\" (", pad, name).unwrap();
                            emit_expr(out, expr);
                            write!(out, ") scalar_unknown)").unwrap();
                        }
                    }
                }
            }
        }

        Stmt::Assign(name, expr) => {
            write!(out, "{}Assign \"{}\" (", pad, name).unwrap();
            emit_expr(out, expr);
            write!(out, ") scalar_unknown").unwrap();
        }

        Stmt::Return(expr) => {
            match expr {
                // Lower ternary in return position to If with two Returns
                Some(Expr::Ternary(cond, then_e, else_e)) => {
                    writeln!(out, "{}If (", pad).unwrap();
                    emit_expr(out, cond);
                    writeln!(out, ")").unwrap();
                    writeln!(out, "{}  (Return (", pad).unwrap();
                    emit_expr(out, then_e);
                    writeln!(out, ") ())").unwrap();
                    writeln!(out, "{}  (Return (", pad).unwrap();
                    emit_expr(out, else_e);
                    write!(out, ") ())").unwrap();
                }
                Some(e) => {
                    write!(out, "{}Return (", pad).unwrap();
                    emit_expr(out, e);
                    write!(out, ") ()").unwrap();
                }
                None => {
                    write!(out, "{}Return (IntLit 0 W32) ()", pad).unwrap();
                }
            }
        }

        Stmt::If(cond, then_stmts, else_stmts) => {
            // Check if this is a null-check pattern
            if let Some(var_name) = is_null_check(cond) {
                writeln!(out, "{}IfNull \"{}\" () () () ()", pad, var_name).unwrap();
                writeln!(out, "{}  (", pad).unwrap();
                emit_stmts(out, then_stmts, indent + 4);
                writeln!(out, ")").unwrap();
                writeln!(out, "{}  (", pad).unwrap();
                emit_stmts(out, else_stmts, indent + 4);
                write!(out, ")").unwrap();
            } else {
                writeln!(out, "{}If (", pad).unwrap();
                emit_expr(out, cond);
                writeln!(out, ")").unwrap();
                writeln!(out, "{}  (", pad).unwrap();
                emit_stmts(out, then_stmts, indent + 4);
                writeln!(out, ")").unwrap();
                writeln!(out, "{}  (", pad).unwrap();
                emit_stmts(out, else_stmts, indent + 4);
                write!(out, ")").unwrap();
            }
        }

        Stmt::ExprStmt(expr) => {
            match expr {
                Expr::Call(func_name, args) => {
                    // Side-effecting helper call: use CallAssign with a throwaway name
                    write!(out, "{}CallAssign \"_\" ", pad).unwrap();
                    emit_helper_ref(out, func_name);
                    write!(out, " [").unwrap();
                    for (i, arg) in args.iter().enumerate() {
                        if i > 0 { write!(out, "; ").unwrap(); }
                        emit_ctype_of_expr(out, arg);
                    }
                    write!(out, "] scalar_unknown").unwrap();
                }
                _ => {
                    // Non-call expression statement: wrap as Nop (expression has no
                    // side effects in our model)
                    write!(out, "{}Nop (* {} *)", pad, emit_expr_brief(expr)).unwrap();
                }
            }
        }

        Stmt::Compound(stmts) => {
            emit_stmts(out, stmts, indent);
        }
    }
}

/// Emit an expression as an F* AST constructor.
fn emit_expr(out: &mut String, expr: &Expr) {
    match expr {
        Expr::IntLit(v, w) => write!(out, "IntLit ({}) {}", v, w).unwrap(),
        Expr::UIntLit(v, w) => write!(out, "UIntLit {} {}", v, w).unwrap(),
        Expr::BoolLit(b) => write!(out, "BoolLit {}", b).unwrap(),
        Expr::VarRef(name, ty) => {
            write!(out, "VarRef \"{}\" {} ()", name, emit_ctype(ty)).unwrap();
        }
        Expr::BinOp(op, lhs, rhs) => {
            write!(out, "BinOp {} (", op).unwrap();
            emit_expr(out, lhs);
            write!(out, ") (").unwrap();
            emit_expr(out, rhs);
            write!(out, ") ()").unwrap();
        }
        Expr::UnaryOp(op, inner) => {
            write!(out, "UnaryOp {} (", op).unwrap();
            emit_expr(out, inner);
            write!(out, ") ()").unwrap();
        }
        Expr::Deref(inner) => {
            write!(out, "Deref (").unwrap();
            emit_expr(out, inner);
            write!(out, ")").unwrap();
        }
        Expr::AddrOf(inner) => {
            write!(out, "AddrOf (").unwrap();
            emit_expr(out, inner);
            write!(out, ")").unwrap();
        }
        Expr::FieldAccess(base, field) => {
            write!(out, "FieldAccess (").unwrap();
            emit_expr(out, base);
            write!(out, ") \"{}\"", field).unwrap();
        }
        Expr::Cast(inner, ty) => {
            write!(out, "Cast {} (", emit_ctype(ty)).unwrap();
            emit_expr(out, inner);
            write!(out, ")").unwrap();
        }
        Expr::Call(name, args) => {
            // Calls in expression position — emit as a comment for now,
            // since our AST doesn't have expression-level calls (only CallAssign)
            write!(out, "(* call: {}(", name).unwrap();
            for (i, arg) in args.iter().enumerate() {
                if i > 0 { write!(out, ", ").unwrap(); }
                write!(out, "{}", emit_expr_brief(arg)).unwrap();
            }
            write!(out, ") *)").unwrap();
        }
        Expr::Ternary(cond, then_e, else_e) => {
            // Ternary is not in our F* AST yet — emit as a comment
            write!(out, "(* ternary: {} ? {} : {} *)",
                emit_expr_brief(cond),
                emit_expr_brief(then_e),
                emit_expr_brief(else_e)
            ).unwrap();
        }
    }
}

/// Check if an expression is a null-check pattern.
fn is_null_check(expr: &Expr) -> Option<&str> {
    match expr {
        Expr::VarRef(name, CType::CPtr(_) | CType::CPtrOrNull(_)) => Some(name),
        Expr::VarRef(name, _) => {
            // Clang often strips the pointer type from the implicit bool cast.
            // If a variable is used as a condition, it's likely a null check.
            // We emit IfNull and let F* decide if it's valid.
            Some(name)
        }
        Expr::BinOp(BinOp::Ne, lhs, rhs) => match (lhs.as_ref(), rhs.as_ref()) {
            (Expr::VarRef(name, _), Expr::UIntLit(0, _)) => Some(name),
            (Expr::UIntLit(0, _), Expr::VarRef(name, _)) => Some(name),
            _ => None,
        },
        _ => None,
    }
}

/// Emit a reference to a helper descriptor from BPF.Helpers.
fn emit_helper_ref(out: &mut String, name: &str) {
    // Map C helper names to our F* helper descriptor names
    let fstar_name = match name {
        "bpf_map_lookup_elem" => "h_map_lookup_elem",
        "bpf_map_update_elem" => "h_map_update_elem",
        "bpf_map_delete_elem" => "h_map_delete_elem",
        "bpf_get_current_pid_tgid" => "h_get_current_pid_tgid",
        "bpf_get_current_uid_gid" => "h_get_current_uid_gid",
        "bpf_get_current_comm" => "h_get_current_comm",
        "bpf_ktime_get_ns" => "h_ktime_get_ns",
        "bpf_ktime_get_boot_ns" => "h_ktime_get_boot_ns",
        "bpf_get_smp_processor_id" => "h_get_smp_processor_id",
        "bpf_get_prandom_u32" => "h_get_prandom_u32",
        "bpf_probe_read_kernel" => "h_probe_read_kernel",
        "bpf_probe_read_user" => "h_probe_read_user",
        "bpf_probe_read" => "h_probe_read",
        "bpf_trace_printk" => "h_trace_printk",
        "bpf_get_current_task" => "h_get_current_task",
        "bpf_tail_call" => "h_tail_call",
        "bpf_perf_event_output" => "h_perf_event_output",
        "bpf_ringbuf_output" => "h_ringbuf_output",
        "bpf_redirect" => "h_redirect",
        "bpf_redirect_map" => "h_redirect_map",
        "bpf_xdp_adjust_head" => "h_xdp_adjust_head",
        "bpf_xdp_adjust_tail" => "h_xdp_adjust_tail",
        "bpf_skb_load_bytes" => "h_skb_load_bytes",
        "bpf_skb_store_bytes" => "h_skb_store_bytes",
        "bpf_fib_lookup" => "h_fib_lookup",
        "bpf_csum_diff" => "h_csum_diff",
        "bpf_sk_lookup_tcp" => "h_sk_lookup_tcp",
        "bpf_sk_lookup_udp" => "h_sk_lookup_udp",
        "bpf_sk_release" => "h_sk_release",
        "bpf_loop" => "h_bpf_loop",
        "bpf_get_stack" => "h_get_stack",
        "bpf_get_stackid" => "h_get_stackid",
        other => {
            // Unknown helper — emit as a comment
            write!(out, "(* unknown helper: {} *) h_get_current_pid_tgid", other).unwrap();
            return;
        }
    };
    write!(out, "{}", fstar_name).unwrap();
}

/// Emit the val_class that a helper call produces.
fn emit_val_class_for_helper(out: &mut String, name: &str) {
    match name {
        "bpf_map_lookup_elem" => write!(out, "(PtrToMapValueOrNull 0 0)").unwrap(),
        "bpf_sk_lookup_tcp" | "bpf_sk_lookup_udp" => {
            write!(out, "(PtrToSocketOrNull 0)").unwrap();
        }
        _ => write!(out, "scalar_unknown").unwrap(),
    }
}

/// Emit the C type of an expression (approximate — for helper arg type lists).
fn emit_ctype_of_expr(out: &mut String, expr: &Expr) {
    match expr {
        Expr::VarRef(_, ty) => write!(out, "{}", emit_ctype(ty)).unwrap(),
        Expr::AddrOf(inner) => {
            write!(out, "(CPtr ").unwrap();
            emit_ctype_of_expr(out, inner);
            write!(out, ")").unwrap();
        }
        Expr::IntLit(_, w) => write!(out, "(CInt {})", w).unwrap(),
        Expr::UIntLit(_, w) => write!(out, "(CUInt {})", w).unwrap(),
        _ => write!(out, "CVoid").unwrap(),
    }
}

fn emit_ctype(ty: &CType) -> String {
    match ty {
        CType::CInt(w) => format!("(CInt {})", w),
        CType::CUInt(w) => format!("(CUInt {})", w),
        CType::CBool => "CBool".to_string(),
        CType::CVoid => "CVoid".to_string(),
        CType::CPtr(inner) => format!("(CPtr {})", emit_ctype(inner)),
        CType::CPtrOrNull(inner) => format!("(CPtr_or_null {})", emit_ctype(inner)),
        CType::CStruct(sd) => format!("(CStruct {{ struct_name = \"{}\"; fields = [] }})", sd.name),
        CType::CArray(elem, n) => format!("(CArray {} {})", emit_ctype(elem), n),
    }
}

fn emit_expr_brief(expr: &Expr) -> String {
    match expr {
        Expr::IntLit(v, _) => format!("{}", v),
        Expr::UIntLit(v, _) => format!("{}", v),
        Expr::BoolLit(b) => format!("{}", b),
        Expr::VarRef(name, _) => name.clone(),
        Expr::BinOp(op, lhs, rhs) => {
            format!("{} {:?} {}", emit_expr_brief(lhs), op, emit_expr_brief(rhs))
        }
        Expr::UnaryOp(op, inner) => format!("{:?}({})", op, emit_expr_brief(inner)),
        Expr::Deref(inner) => format!("*{}", emit_expr_brief(inner)),
        Expr::AddrOf(inner) => format!("&{}", emit_expr_brief(inner)),
        Expr::FieldAccess(base, field) => format!("{}.{}", emit_expr_brief(base), field),
        Expr::Cast(inner, _) => emit_expr_brief(inner),
        Expr::Call(name, args) => {
            let args_str: Vec<String> = args.iter().map(|a| emit_expr_brief(a)).collect();
            format!("{}({})", name, args_str.join(", "))
        }
        Expr::Ternary(c, t, e) => {
            format!("{} ? {} : {}", emit_expr_brief(c), emit_expr_brief(t), emit_expr_brief(e))
        }
    }
}
