//! Surface AST emitter.
//!
//! Emits F* source that uses the surface AST types from BPF.AST.Surface.
//! This is dramatically simpler than the indexed emitter because:
//! - No type indices to compute
//! - No variable context threading
//! - No squash proof placeholders
//! - No val_class computation
//! - Just print constructor names and recurse

use std::fmt::Write;

use super::fstar_ast::*;

/// Emit a complete F* module using the surface AST + tactic approach.
pub fn emit_surface_module(obj: &BpfObject, module_name: &str) -> String {
    let mut out = String::new();

    writeln!(out, "(* Auto-generated by bpf-verifier from {} *)", obj.source_file).unwrap();
    writeln!(out, "module {module_name}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "open BPF.AST.Types").unwrap();
    writeln!(out, "open BPF.AST.Expr").unwrap();
    writeln!(out, "open BPF.AST.Surface").unwrap();
    writeln!(out, "open BPF.AST.Elaborate").unwrap();
    writeln!(out, "open BPF.AST.Tactic").unwrap();
    writeln!(out).unwrap();

    for prog in &obj.progs {
        emit_prog(&mut out, prog);
        writeln!(out).unwrap();
    }

    out
}

fn emit_prog(out: &mut String, prog: &BpfProg) {
    let fstar_prog_type = section_to_prog_type(&prog.section);

    writeln!(out, "(* Programme: {} SEC(\"{}\") *)", prog.name, prog.section).unwrap();
    writeln!(out).unwrap();

    // Emit the surface programme definition
    writeln!(out, "let surface_{} : s_prog = {{", prog.name).unwrap();
    writeln!(out, "  sp_name = \"{}\";", prog.name).unwrap();
    writeln!(out, "  sp_section = \"{}\";", prog.section).unwrap();
    writeln!(out, "  sp_param_name = \"{}\";", prog.param_name).unwrap();
    write!(out, "  sp_body = ").unwrap();
    emit_surface_stmt(out, &prog.body, 4);
    writeln!(out, ";").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Emit the proof obligation
    writeln!(
        out,
        "let _ : squash (check_ok {fstar_prog_type} surface_{} == true) =",
        prog.name
    )
    .unwrap();
    writeln!(out, "  _ by (ast_check_tac ())").unwrap();
}

/// Emit a list of statements as nested SSeq.
fn emit_surface_stmt(out: &mut String, stmts: &[Stmt], indent: usize) {
    let pad = " ".repeat(indent);
    match stmts.len() {
        0 => write!(out, "SNop").unwrap(),
        1 => emit_single_stmt(out, &stmts[0], indent),
        _ => {
            write!(out, "SSeq (\n{pad}  ").unwrap();
            emit_single_stmt(out, &stmts[0], indent + 2);
            write!(out, ")\n{pad}  (").unwrap();
            emit_surface_stmt(out, &stmts[1..], indent + 2);
            write!(out, ")").unwrap();
        }
    }
}

fn emit_single_stmt(out: &mut String, stmt: &Stmt, indent: usize) {
    let pad = " ".repeat(indent);
    match stmt {
        Stmt::Declare(name, ty, init) => {
            match init {
                None => {
                    write!(out, "SDeclare \"{name}\" {} None", emit_ctype(ty)).unwrap();
                }
                Some(Expr::Call(func_name, args)) => {
                    // Declaration with helper call init: lower to
                    // SSeq (SDeclare) (SCallStmt name func args)
                    write!(out, "SSeq (SDeclare \"{name}\" {} None)\n", emit_ctype(ty)).unwrap();
                    write!(out, "{pad}  (SCallStmt \"{name}\" \"{func_name}\" [").unwrap();
                    for (i, arg) in args.iter().enumerate() {
                        if i > 0 {
                            write!(out, "; ").unwrap();
                        }
                        emit_surface_expr(out, arg);
                    }
                    write!(out, "])").unwrap();
                }
                Some(expr) => {
                    write!(out, "SDeclare \"{name}\" {} (Some (", emit_ctype(ty)).unwrap();
                    emit_surface_expr(out, expr);
                    write!(out, "))").unwrap();
                }
            }
        }

        Stmt::Assign(name, expr) => {
            write!(out, "SAssign \"{name}\" (").unwrap();
            emit_surface_expr(out, expr);
            write!(out, ")").unwrap();
        }

        Stmt::Return(expr) => {
            match expr {
                Some(e) => {
                    write!(out, "SReturn (Some (").unwrap();
                    emit_surface_expr(out, e);
                    write!(out, "))").unwrap();
                }
                None => {
                    write!(out, "SReturn None").unwrap();
                }
            }
        }

        Stmt::If(cond, then_stmts, else_stmts) => {
            write!(out, "SIf (").unwrap();
            emit_surface_expr(out, cond);
            write!(out, ")\n{pad}  (").unwrap();
            emit_surface_stmt(out, then_stmts, indent + 2);
            write!(out, ")\n{pad}  (").unwrap();
            emit_surface_stmt(out, else_stmts, indent + 2);
            write!(out, ")").unwrap();
        }

        Stmt::ExprStmt(Expr::Call(func_name, args)) => {
            // Side-effecting helper call → SCallStmt with throwaway name
            write!(out, "SCallStmt \"_\" \"{func_name}\" [").unwrap();
            for (i, arg) in args.iter().enumerate() {
                if i > 0 {
                    write!(out, "; ").unwrap();
                }
                emit_surface_expr(out, arg);
            }
            write!(out, "]").unwrap();
        }

        Stmt::ExprStmt(_) => {
            write!(out, "SNop").unwrap();
        }

        Stmt::Compound(stmts) => {
            emit_surface_stmt(out, stmts, indent);
        }

        Stmt::Goto(_) | Stmt::Label(_, _) | Stmt::Break => {
            write!(out, "SNop").unwrap();
        }

        Stmt::Switch(_, _) => {
            // TODO: lower switch to nested SIf
            write!(out, "SNop").unwrap();
        }
    }
}

fn emit_surface_expr(out: &mut String, expr: &Expr) {
    match expr {
        Expr::IntLit(v, w) => write!(out, "SIntLit ({v}) {w}").unwrap(),
        Expr::UIntLit(v, w) => write!(out, "SUIntLit {v} {w}").unwrap(),
        Expr::BoolLit(b) => write!(out, "SBoolLit {b}").unwrap(),

        Expr::VarRef(name, _) => {
            write!(out, "SVarRef \"{name}\"").unwrap();
        }

        Expr::BinOp(op, lhs, rhs) => {
            write!(out, "SBinOp {op} (").unwrap();
            emit_surface_expr(out, lhs);
            write!(out, ") (").unwrap();
            emit_surface_expr(out, rhs);
            write!(out, ")").unwrap();
        }

        Expr::UnaryOp(op, inner) => {
            write!(out, "SUnaryOp {op} (").unwrap();
            emit_surface_expr(out, inner);
            write!(out, ")").unwrap();
        }

        Expr::Deref(inner) => {
            write!(out, "SDeref (").unwrap();
            emit_surface_expr(out, inner);
            write!(out, ")").unwrap();
        }

        Expr::AddrOf(inner) => {
            write!(out, "SAddrOf (").unwrap();
            emit_surface_expr(out, inner);
            write!(out, ")").unwrap();
        }

        Expr::FieldAccess(base, field) => {
            write!(out, "SFieldAccess (").unwrap();
            emit_surface_expr(out, base);
            write!(out, ") \"{field}\"").unwrap();
        }

        Expr::Cast(inner, ty) => {
            write!(out, "SCast {} (", emit_ctype(ty)).unwrap();
            emit_surface_expr(out, inner);
            write!(out, ")").unwrap();
        }

        Expr::Call(name, args) => {
            write!(out, "SCall \"{name}\" [").unwrap();
            for (i, arg) in args.iter().enumerate() {
                if i > 0 {
                    write!(out, "; ").unwrap();
                }
                emit_surface_expr(out, arg);
            }
            write!(out, "]").unwrap();
        }

        Expr::Ternary(cond, then_e, else_e) => {
            // Lower to a call expression (the checker doesn't handle ternary;
            // it should be lowered at the statement level by the converter)
            write!(out, "SIntLit 0 W32 (* ternary: ").unwrap();
            emit_surface_expr(out, cond);
            write!(out, " ? ").unwrap();
            emit_surface_expr(out, then_e);
            write!(out, " : ").unwrap();
            emit_surface_expr(out, else_e);
            write!(out, " *)").unwrap();
        }

        Expr::ArraySubscript(base, index) => {
            write!(out, "SDeref (SBinOp Add (").unwrap();
            emit_surface_expr(out, base);
            write!(out, ") (").unwrap();
            emit_surface_expr(out, index);
            write!(out, "))").unwrap();
        }

        Expr::SizeOf(size) => {
            write!(out, "SSizeOf {size}").unwrap();
        }

        Expr::StringLit(_) => {
            write!(out, "SIntLit 0 W64").unwrap();
        }

        Expr::StmtExpr(_, final_expr) => {
            emit_surface_expr(out, final_expr);
        }

        Expr::InitList(_) => {
            write!(out, "SIntLit 0 W32").unwrap();
        }
    }
}

fn emit_ctype(ty: &CType) -> String {
    match ty {
        CType::CInt(w) => format!("(CInt {w})"),
        CType::CUInt(w) => format!("(CUInt {w})"),
        CType::CBool => "CBool".to_string(),
        CType::CVoid => "CVoid".to_string(),
        CType::CPtr(inner) => format!("(CPtr {})", emit_ctype(inner)),
        CType::CPtrOrNull(inner) => format!("(CPtr_or_null {})", emit_ctype(inner)),
        CType::CStruct(sd) => {
            if sd.fields.is_empty() {
                format!(
                    "(CStruct {{ struct_name = \"{}\"; fields = [] }})",
                    sd.name
                )
            } else {
                let fields: Vec<String> = sd
                    .fields
                    .iter()
                    .map(|(name, ty)| format!("(\"{name}\", {})", emit_ctype(ty)))
                    .collect();
                format!(
                    "(CStruct {{ struct_name = \"{}\"; fields = [{}] }})",
                    sd.name,
                    fields.join("; ")
                )
            }
        }
        CType::CArray(elem, n) => format!("(CArray {} {n})", emit_ctype(elem)),
    }
}

fn section_to_prog_type(section: &str) -> &'static str {
    match section {
        "socket_filter" | "socket" => "ProgSocketFilter",
        "xdp" => "ProgXDP",
        "kprobe" | "kretprobe" => "ProgKprobe",
        "tracepoint" | "tp" => "ProgTracepoint",
        "perf_event" => "ProgPerfEvent",
        "cgroup/skb" | "cgroup_skb" => "ProgCgroupSkb",
        "cgroup/sock" | "cgroup_sock" => "ProgCgroupSock",
        s if s.starts_with("kprobe/") || s.starts_with("kretprobe/") => "ProgKprobe",
        s if s.starts_with("tracepoint/") || s.starts_with("tp/") => "ProgTracepoint",
        s if s.starts_with("raw_tracepoint/") || s.starts_with("raw_tp/") => {
            "ProgRawTracepoint"
        }
        s if s.starts_with("xdp") => "ProgXDP",
        s if s.starts_with("lsm/") => "ProgSocketFilter",
        s if s.starts_with("fentry/") || s.starts_with("fexit/") => "ProgSocketFilter",
        s if s.starts_with("cgroup/") => "ProgCgroupSkb",
        s if s.starts_with("tc") || s.starts_with("classifier") => "ProgSchedCls",
        _ => "ProgSocketFilter",
    }
}
